### ISSUE TITLE
Getting started todo list

### ISSUE THREAD

**Issue by noobling** [noobling/prof-comp#1]
- [x] Email auditor
- [x] Set up important date reminders on facebook chat
- [x] Send out project list
- [x] Set up client meeting times
- [x] Set mentor meeting times

**Comment by m-Dorrell** [comment]
We have fulfilled these tasks
