### ISSUE TITLE
David's todo before next meeting

### ISSUE THREAD

**Issue by noobling** [noobling/prof-comp#27]
- [x] Password resets
- [ ] Implement IE support
- [x] Add sentry error logging
- [x] Add graphing
- [x] Make excel sheet data user friendly
- [x] Fix bug when trying to download spreadsheet `Error: Sheet name cannot contain : \ / ? * [ ]`

**Comment by noobling** [comment]
Meeting has concluded
