### ISSUE TITLE
Michael's todo before next meeting 

### ISSUE THREAD

**Issue by m-Dorrell** [noobling/prof-comp#28]
- [x] Research swift syntax
- [x] Do a swift tutorial
- [x] Discuss plans with Taige

**Comment by m-Dorrell** [comment]
Completed goals successfully
