### ISSUE TITLE
Zihao's TODO before next meeting

### ISSUE THREAD

**Issue by 1shoot101kill** [noobling/prof-comp#30]
- [x] data verification(not null input)
- [x] add event listening
- [ ] research http resonse
- [ ] local database

**Comment by noobling** [comment]
Closing meeting passed
