### ISSUE TITLE
Taige's Todo before next Meeting

### ISSUE THREAD

**Issue by tigertiggs** [noobling/prof-comp#31]
Field - iOS app
- [ ] Implement the framework (ResearchKit) into a prototype
- [ ] Implement the required questionnaire 
- [ ] Research and implement the data management solutions for ResearchKit
- [ ] Find a way to user test the app
- [ ] Complete data visualisation

**Comment by noobling** [comment]
Thanks for the issue, I would encourage you to be a bit more specific that way it is well defined what you will be doing and we can measure that progress.

**Comment by noobling** [comment]
Closing this meeting has passed
