### ISSUE TITLE
Joshua's todo before next meeting

### ISSUE THREAD

**Issue by Brutnip** [noobling/prof-comp#32]
- [x] Complete information text for all q's
- [x] Refine layout
- [ ] Refine theme
- [ ] Implement local storage (stretch)
- [ ] Add basic analytics (stretch)

**Comment by noobling** [comment]
Closing this meeting has passed
