### ISSUE TITLE
Michael's TODO before next meeting

### ISSUE THREAD

**Issue by m-Dorrell** [noobling/prof-comp#34]
- [ ] Build a very basic iOS app
    - [x] iOS branch
    - [x] Tabbed app
    - [x] Implement ResearchKit
    - [ ] Survey functions (returns required info after prompting)
    - [ ] Basic layout described
        - [ ] Sleep Journal layout (samples how information will be presented)
        - [ ] Setting page layout (Shows how settings will look, without any back-end)
- [ ] Visualisations (Stretch goal for this week)

**Comment by m-Dorrell** [comment]
Began work on iOS app, but other work got in the way of completing my goals

Will aim to complete all of it and more by next week
