### ISSUE TITLE
David's TODO before meeting on 10th October

### ISSUE THREAD

**Issue by noobling** [noobling/prof-comp#35]
- [ ] Make a more accurate time picker
- [ ] Use email for identification for the user
- [ ] Complete the settings page
- [ ] Make improvements to app based on user feedback
