### ISSUE TITLE
Zihao's TODO before Week 10 meeting

### ISSUE THREAD

**Issue by 1shoot101kill** [noobling/prof-comp#36]
- [ ] Add 'Menu' function to all Activities
- [ ] Implement http request
- [ ] Implement Local database(if http complete)
