### ISSUE TITLE
Michael'd TODO before next meeting

### ISSUE THREAD

**Issue by m-Dorrell** [noobling/prof-comp#38]
- [ ] Survey fully functional
    - [x] All questions implemented
    - [ ] 'Not Applicable' questions don't show up
    - [x] Correct answer formats
    - [ ] Returns correct in JSON format
- [ ] Other tabs filled out
    - [ ] Settings page has correct layout
    - [ ] Sleep diary page has example layout
    - [ ] Visualization can present an example graph (Stretch)

**Comment by m-Dorrell** [comment]
Taige took over N/A questions task

Can return as a JSON format, but requires more work to return in intended format

**Comment by m-Dorrell** [comment]
Issue closed due to dropping iOS implementation
