### ISSUE TITLE
TODO before meeting on 17th October

### ISSUE THREAD

**Issue by noobling** [noobling/prof-comp#41]
- [x] Finalise the app
- [x] Write up user acceptance tests
- [x] Organise client meeting to complete a project retrospective
