### ISSUE TITLE
Sprint 3 Checklist

### ISSUE THREAD

**Issue by noobling** [noobling/prof-comp#43]
- [ ] Singed of UAT tests
- [ ] Minutes on Client Retrospective
- [ ] Minutes on internal retrospective
- [ ] Completed timesheets and booked hours
- [ ] Completed time analysis for iOS, Android and Web app
- [ ] Documentation for application

**Comment by m-Dorrell** [comment]
I'll write up the minutes on internal retrospective into a more fleshed out document
